#stage:1 build
FROM node:22-slim AS build
WORKDIR /app

COPY package*.json ./
RUN npm install 

COPY . .

#stage:2 production
FROM node:22-slim AS production
WORKDIR /app

COPY --from=build /app ./
EXPOSE 5001

ENTRYPOINT ["node", "server.js"]


